name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: antonysabu1
          SETTING_JSON: profile-3d-contrib/settings.json
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update 3D contribution graph [skip ci]"
            git push
          fi